"""add post_taboola_table4

Revision ID: 2aec2128bada
Revises: d0caec83c758
Create Date: 2023-09-12 10:15:13.962260

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '2aec2128bada'
down_revision = 'd0caec83c758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('report_taboola_id_fkey', 'report', type_='foreignkey')
    op.drop_column('report', 'taboola_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('taboola_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('report_taboola_id_fkey', 'report', 'taboola', ['taboola_id'], ['id'])
    # ### end Alembic commands ###
