"""add taboola_id

Revision ID: 33026de3f6b6
Revises: 8b68e47310b2
Create Date: 2023-09-11 20:13:41.271945

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '33026de3f6b6'
down_revision = '8b68e47310b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_taboola_table', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_taboola_table', 'taboola_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('post_taboola_table_un', 'post_taboola_table', type_='unique')
    op.create_index(op.f('ix_post_taboola_table_post_id'), 'post_taboola_table', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_taboola_table_taboola_id'), 'post_taboola_table', ['taboola_id'], unique=False)
    op.add_column('report', sa.Column('taboola_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'taboola', ['taboola_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'taboola_id')
    op.drop_index(op.f('ix_post_taboola_table_taboola_id'), table_name='post_taboola_table')
    op.drop_index(op.f('ix_post_taboola_table_post_id'), table_name='post_taboola_table')
    op.create_unique_constraint('post_taboola_table_un', 'post_taboola_table', ['id'])
    op.alter_column('post_taboola_table', 'taboola_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_taboola_table', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
