"""add post_taboola_table1

Revision ID: 345071af008a
Revises: 33026de3f6b6
Create Date: 2023-09-12 10:01:30.828462

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '345071af008a'
down_revision = '33026de3f6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_taboola_table', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_taboola_table', 'taboola_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_post_taboola_table_post_id', table_name='post_taboola_table')
    op.drop_index('ix_post_taboola_table_taboola_id', table_name='post_taboola_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_taboola_table_taboola_id', 'post_taboola_table', ['taboola_id'], unique=False)
    op.create_index('ix_post_taboola_table_post_id', 'post_taboola_table', ['post_id'], unique=False)
    op.alter_column('post_taboola_table', 'taboola_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_taboola_table', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
