"""add post_taboola_table7

Revision ID: 3fcedaded76d
Revises: b164798d3c12
Create Date: 2023-09-13 19:59:57.912883

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '3fcedaded76d'
down_revision = 'b164798d3c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taboola', sa.Column('create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='添加时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taboola', 'create')
    # ### end Alembic commands ###
