"""report_post

Revision ID: 6a62f76fb74b
Revises: 6db7b0ee543f
Create Date: 2023-09-07 13:48:29.219651

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '6a62f76fb74b'
down_revision = '6db7b0ee543f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
