"""report_ip

Revision ID: 6db7b0ee543f
Revises: ab9de6e97024
Create Date: 2023-09-05 16:11:46.303040

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '6db7b0ee543f'
down_revision = 'ab9de6e97024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('visitor_ip_browser_info_id_fkey', 'visitor_ip', type_='foreignkey')
    op.drop_column('visitor_ip', 'browser_info_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor_ip', sa.Column('browser_info_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='访客信息'))
    op.create_foreign_key('visitor_ip_browser_info_id_fkey', 'visitor_ip', 'browser_info', ['browser_info_id'], ['id'])
    # ### end Alembic commands ###
