"""910-1

Revision ID: 8b68e47310b2
Revises: 932471d08f89
Create Date: 2023-09-10 11:57:20.060098

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '8b68e47310b2'
down_revision = '932471d08f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('browser_info', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'browser_info', 'domain', ['domain_id'], ['id'])
    op.alter_column('post', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('report', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'domain', ['domain_id'], ['id'])
    op.add_column('taboola', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'taboola', 'domain', ['domain_id'], ['id'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.String(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=72),
               existing_nullable=False)
    op.drop_constraint(None, 'taboola', type_='foreignkey')
    op.drop_column('taboola', 'domain_id')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'domain_id')
    op.alter_column('post', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'browser_info', type_='foreignkey')
    op.drop_column('browser_info', 'domain_id')
    # ### end Alembic commands ###
