"""domain or post1

Revision ID: 932471d08f89
Revises: 6a62f76fb74b
Create Date: 2023-09-07 18:59:21.838566

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '932471d08f89'
down_revision = '6a62f76fb74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'domain', ['domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'domain_id')
    # ### end Alembic commands ###
