"""report

Revision ID: ab9de6e97024
Revises: da84a0acb4b1
Create Date: 2023-09-05 15:26:14.774281

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ab9de6e97024'
down_revision = 'da84a0acb4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False, comment='推广网址'),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('taboola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('click_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_item_id', sa.String(length=15), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('browser_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint_id', sa.String(length=15), nullable=False, comment='指纹ID'),
    sa.Column('user_agent', sa.String(length=255), nullable=False, comment='浏览器ua'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='访问时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True, comment='帖子信息'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_info_fingerprint_id'), 'browser_info', ['fingerprint_id'], unique=False)
    op.create_table('post_taboola_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('taboola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['taboola_id'], ['taboola.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'taboola_id')
    )
    op.create_table('visitor_ip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False, comment='访客ip'),
    sa.Column('browser_info_id', sa.Integer(), nullable=True, comment='访客信息'),
    sa.ForeignKeyConstraint(['browser_info_id'], ['browser_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False, comment='推广网址'),
    sa.Column('is_page', sa.Boolean(), nullable=False, comment='是否翻页'),
    sa.Column('create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='添加时间'),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('visitor_ip', sa.Integer(), nullable=False),
    sa.Column('browser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['browser_id'], ['browser_info.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['visitor_ip'], ['visitor_ip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('visitor_ip')
    op.drop_table('post_taboola_table')
    op.drop_index(op.f('ix_browser_info_fingerprint_id'), table_name='browser_info')
    op.drop_table('browser_info')
    op.drop_table('taboola')
    op.drop_table('post')
    # ### end Alembic commands ###
