"""add post_taboola_table6

Revision ID: b164798d3c12
Revises: baae28991807
Create Date: 2023-09-12 10:52:07.794884

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b164798d3c12'
down_revision = 'baae28991807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_taboola_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('taboola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['taboola_id'], ['taboola.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'taboola_id')
    )
    op.add_column('report', sa.Column('taboola_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'taboola', ['taboola_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'taboola_id')
    op.drop_table('post_taboola_table')
    # ### end Alembic commands ###
