"""add post_taboola_table5

Revision ID: baae28991807
Revises: 2aec2128bada
Create Date: 2023-09-12 10:16:08.084763

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'baae28991807'
down_revision = '2aec2128bada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
