"""add post_taboola_table3

Revision ID: d0caec83c758
Revises: bb0eff306cd6
Create Date: 2023-09-12 10:12:11.746558

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'd0caec83c758'
down_revision = 'bb0eff306cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_taboola_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_taboola_table',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taboola_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_taboola_table_post_id_fkey'),
    sa.ForeignKeyConstraint(['taboola_id'], ['taboola.id'], name='post_taboola_table_taboola_id_fkey')
    )
    # ### end Alembic commands ###
